#!/bin/bash

ready_for_commit(){

        echo "DOCSTRING UPDATE: passed"


        echo " "
        echo "--------------------------------"
        echo "-------- COMMIT SECTION --------"
        echo "--------------------------------"
        echo " "
        echo "Amazing work, let's get ready to commit and push then! :) "

        read -p "Ready to fetch origin? " yn
        case $yn in
            [Yy]* ) echo -e "RECENTLY UPDATED: passed \n";;
            [Nn]* ) echo "Ok, later." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        git fetch origin
        git pull

        read -p "Did you really think through everything that could wrong? " yn
        case $yn in
            [Yy]* ) echo -e "POINT OF NO RETURN: passed \n";;
            [Nn]* ) echo "Think, and then rethink. Check and then doublecheck." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        read -p "Ready to commit then? " yn
        case $yn in
            [Yy]* ) echo -e "Let's do this! You're ready to commit :) \n";;
            [Nn]* ) echo "That's right, better be safe than sorry" ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

}


remove_tempfiles(){

    rm saved_model.h5
    rm saved_model.json
    rm saved_model.x
    rm strings.h5
    rm strings.json
    rm strings.x
    rm test_data.csv
    rm test_data.json
    rm test_data.msgpack
    rm test_model.h5
    rm test_model.json
    rm test_model.x
    rm train.png
}

sanity_check(){

        echo " "
    	echo "--------------------------------"
        echo "-------- SANITY CHECK ----------"
        echo "--------------------------------"
        echo " "

        read -p "Have you tested thoroughly? " yn
        case $yn in
        	[Yy]* ) echo -e "THOROUGH TESTING: passed \n";;
            [Nn]* ) echo "Time to do it now then." ; exit;;
    		* ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        read -p "Did you make according changes to test_script.py? " yn
        case $yn in
        	[Yy]* ) echo -e "TEST SCRIPT REVIEW: passed \n";;
            [Nn]* ) echo "Well, you know better than that." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        read -p "Are docstrings up-to-date? " yn
        case $yn in
        	[Yy]* ) echo -e "DOCSTRING UPDATE: passed \n";;
            [Nn]* ) echo "Auch...come back when it's done." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        read -p "Are you in an python/conda environment? " yn
        case $yn in
            [Yy]* ) echo -e "DOCSTRING UPDATE: passed \n";;
            [Nn]* ) echo "You know that's not the way to do it." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        read -p "Did you check that the API namespace is clean?" yn
        case $yn in
            [Yy]* ) echo -e "API NAMESPACE INTEGRITY: passed \n";;
            [Nn]* ) echo "This is a key point you know..." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        read -p "Code is pep8? " yn
        case $yn in
            [Yy]* ) echo -e "PEP8 Check: passed \n";;
            [Nn]* ) echo "Some cleaning up to do I see." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        read -p "WIKI is updated with version changes? " yn
        case $yn in
            [Yy]* ) echo -e "Version changes check: passed \n";;
            [Nn]* ) echo "You do know there is NO way out of it." ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

     
        read -p "Ready for a local test then eh? " yn
        case $yn in
            [Yy]* ) python test_script.py; STATUS=($?);;
            [Nn]* ) echo "Not feeling confident yet, you know what to do ;)" ; exit;;
            * ) echo "Yes (y) or no (n) answers only."; break;;
        esac

        if [ "$STATUS" == "0" ];
        then 

            echo -e "TESTSCRIPT ON LOCAL ENV: passed \n"
            
            remove_tempfiles
            ready_for_commit

        else 
            echo " "
            echo "KABOOM!!!"
            echo " "
            echo "Right...and this is what you were thinking of committing? Nice try."
            echo " "
            break
        fi 
}

clear

sanity_check



